image: node:latest

stages:
  - installation
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: installation
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

Build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm run build
  only:
    - master

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r ./dist/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master