image: node:9

stages:
  - installation
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: installation
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

Build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm run build
  only:
    - master

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r ./dist/* .public
    - mv .public public
    - git clone --depth 1 https://abhijithvijayan:$GITHUB_ACCESS_TOKEN@github.com/abhijithvijayan/abhijithvijayan.github.io.git gh-pages
    - rm -r gh-pages/*
    - cp -r ./dist/* gh-pages
    - cd gh-pages
    - git config user.email "34790378+abhijithvijayan@users.noreply.github.com"
    - git config --global user.name "abhijithvijayan"
    - git add -A
    - git commit -m "Build from $CI_SERVER_NAME $CI_PIPELINE_ID"
    - git push origin master
  artifacts:
    paths:
      - public
  only:
    - master